name: 🚀 New Project Submission
description: Submit a new project to OpenPlayground
title: "[New Project]: "
labels: ["new-project", "needs-review"]

body:
  - type: markdown
    attributes:
      value: |
        Want to add a project? Great! Fill out this form and then submit a PR.

        **Before submitting:**
        - Test your project locally
        - Make sure your project follows the repository structure
        - Read the [CONTRIBUTING.md](../CONTRIBUTING.md) guidelines

  - type: input
    id: project_name
    attributes:
      label: Project Name
      placeholder: e.g., "Weather Dashboard"
    validations:
      required: true

  - type: dropdown
    id: project_type
    attributes:
      label: Project Type
      description: Select the type of project you are submitting
      options:
        - Frontend (HTML/CSS/JS)
        - Full-Stack (Frontend + Backend)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - utility
        - game
        - puzzle
        - fun
        - productivity
        - experimental
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: Brief description (max 100 characters for card display)
      placeholder: A weather app that shows current conditions and forecasts.
    validations:
      required: true

  - type: textarea
    id: tech_stack
    attributes:
      label: Tech Stack
      placeholder: |
        - Frontend: HTML, CSS, JS / React / Vue
        - Backend: Node.js / Flask / Django / Firebase
        - Database: MongoDB / SQLite / PostgreSQL

  - type: textarea
    id: features
    attributes:
      label: Key Features
      placeholder: |
        - Feature 1
        - Feature 2
        - Feature 3

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots or screen recordings of your project
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have tested my project locally
          required: true
        - label: My project follows the repository structure
          required: true
        - label: My project is responsive (if frontend)
          required: true
        - label: I will add my project to projects.json (NOT index.html)
          required: true
        - label: I have included setup instructions for backend (if full-stack)
          required: false
